-- 운영툴 + 데이터 수집 테이블 (v12)
create table if not exists eoullim_counsel (
  id bigint generated by default as identity primary key,
  nick text, contact_method text, contact text, pref text, message text,
  status text default 'new', created_at timestamptz default now()
);
create table if not exists eoullim_checks (
  id bigint generated by default as identity primary key,
  test text, score int, level text, nick text, age text, contact text,
  created_at timestamptz default now()
);
alter table eoullim_counsel enable row level security;
alter table eoullim_checks enable row level security;

drop policy if exists "counsel_insert" on eoullim_counsel;
create policy "counsel_insert" on eoullim_counsel for insert with check (true);
drop policy if exists "counsel_update" on eoullim_counsel;
create policy "counsel_update" on eoullim_counsel for update using (true) with check (true);
drop policy if exists "checks_insert" on eoullim_checks;
create policy "checks_insert" on eoullim_checks for insert with check (true);

-- 운영자 삭제 RPC (비밀번호 검증 후 삭제)
create or replace function admin_delete_post(post_id bigint, pw text)
returns boolean language plpgsql security definer as $$
begin
  if pw <> 'artintouch!' then return false; end if;
  delete from eoullim_board where id = post_id;
  return true;
end $$;
