-- 어울림 마음쉼터 — 게시판/신청곡 Supabase 테이블
-- 실행 위치: Supabase Dashboard → SQL Editor
-- 목적: 게시판 글을 모든 방문자가 공유 (GMI와 동일한 Supabase 프로젝트 재활용 or 신규)

-- 1) 마음 게시판
create table if not exists eoullim_board (
  id bigint generated by default as identity primary key,
  nick text,                    -- 닉네임 (nullable)
  text text not null,           -- 내용
  secret boolean default false, -- 비밀글
  owner_key text,               -- 작성자 브라우저 키 (비밀글 본인 확인용)
  warm int default 0,           -- 따뜻해요 수
  warm_voters text[] default '{}',  -- 중복방지용 키 배열
  created_at timestamptz default now()
);

-- 2) 신청곡
create table if not exists eoullim_songs (
  id bigint generated by default as identity primary key,
  title text not null,
  why text,
  created_at timestamptz default now()
);

-- 3) RLS 정책 — 누구나 읽기/쓰기 가능 (익명 사이트), warm_voters로 따뜻해요 중복만 방지
alter table eoullim_board enable row level security;
alter table eoullim_songs enable row level security;

drop policy if exists "board_public_read" on eoullim_board;
create policy "board_public_read" on eoullim_board for select using (true);

drop policy if exists "board_public_insert" on eoullim_board;
create policy "board_public_insert" on eoullim_board for insert with check (true);

drop policy if exists "board_public_update" on eoullim_board;  -- 따뜻해요 카운트 갱신용
create policy "board_public_update" on eoullim_board for update using (true) with check (true);

drop policy if exists "songs_public_read" on eoullim_songs;
create policy "songs_public_read" on eoullim_songs for select using (true);

drop policy if exists "songs_public_insert" on eoullim_songs;
create policy "songs_public_insert" on eoullim_songs for insert with check (true);

-- 4) 비밀글 내용은 서버에서도 필터링 (선택 — 프론트에서 마스킹하지만 RDS 레벨 이중 안전장치)
-- view: 비밀글은 내용 대신 마커만 노출
create or replace view eoullim_board_public as
  select id, nick, case when secret then null else text end as text,
         secret, owner_key, warm, warm_voters, created_at
  from eoullim_board;
