-- v13: 운영자 답글 + 플레이리스트 + 삭제 권한
alter table eoullim_board add column if not exists admin_reply text;

create table if not exists eoullim_playlist (
  id bigint generated by default as identity primary key,
  title text not null,
  search_q text,
  pos int default 0,
  created_at timestamptz default now()
);
alter table eoullim_playlist enable row level security;
drop policy if exists "pl_read" on eoullim_playlist;
create policy "pl_read" on eoullim_playlist for select using (true);
drop policy if exists "pl_write" on eoullim_playlist;
create policy "pl_write" on eoullim_playlist for insert with check (true);
drop policy if exists "pl_del" on eoullim_playlist;
create policy "pl_del" on eoullim_playlist for delete using (true);

-- 신청곡: 읽기/삭제 권한 (운영툴 관리용)
drop policy if exists "songs_del" on eoullim_songs;
create policy "songs_del" on eoullim_songs for delete using (true);
drop policy if exists "songs_write" on eoullim_songs;
create policy "songs_write" on eoullim_songs for insert with check (true);
drop policy if exists "songs_read2" on eoullim_songs;
create policy "songs_read2" on eoullim_songs for select using (true);

-- 뷰 갱신 (admin_reply 포함)
create or replace view eoullim_board_public as
  select id, nick, case when secret then null else text end as text,
         secret, owner_key, warm, cheer, admin_reply, react_voters, created_at
  from eoullim_board;
